config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Area 1: Admin
  namespace :admin do
    root to: 'home#index'
    match 'sign_in', :ur => "authentication#sign_in", via: :get
    match 'login', :to => "authentication#login", via: :post
    resources :products
    resources :kirsch_products
    resources :users
    resources :orders, only: [ :index ]
    namespace :orders do
      get :mark_paid, as: :mark_paid
      get :mark_sent, as: :mark_sent
      get :mark_fake, as: :mark_fake
      get :ordered_at_kirsch, as: :ordered_at_kirsch
      get :fake
    end
    get 'empty', to: 'home#empty'
    get 'reporting', to: 'home#reporting'
  end

  # Area 2: customer
  root to: 'main#landing_page'
  resources :orders, only: [:new, :create, :show]
  post 'orders/entry', to: 'orders#entry', as: 'entry'
  resources :products, only: [:show]

  get 'scotch', to: 'main#scotch', as: :scotch
  get 'whiskey', to: 'main#whiskey', as: :whiskey
  get 'rum', to: 'main#rum', as: :rum
  get 'gin', to: 'main#gin', as: :gin
  get 'andere', to: 'main#andere', as: :andere

  # Area 3: static pages
  get 'imprint', to: 'main#imprint'
  get 'agb', to: 'main#agb'
  get 'therapien', to: 'main#therapien'
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def landing_page
    # Neue Nutzer sollen gleich alle Produkte sehen. Lieber nur Angebote?
    @products = Product.all
  end

  def imprint
  end

  def agb
  end

  def scotch
  end

  def whiskey
  end

  def rum
  end

  def gin
  end

  def andere
  end

end

app/views/main/agb.html.erb
<h1>
  Allgemeine Geschäftsbedingungen
</h1>
<h3>
  1. Inhalt des Onlineangebotes
</h3>
<p>
  Die Autoren übernehmen keinerlei Gewähr für die Aktualität, Korrektheit, Vollständigkeit oder Qualität der bereitgestellten Informationen. Haftungsansprüche gegen den Autor, welche sich auf Schäden materieller oder ideeller Art beziehen, die durch die Nutzung oder Nichtnutzung der dargebotenen Informationen bzw. durch die Nutzung fehlerhafter und unvollständiger Informationen verursacht wurden, sind grundsätzlich ausgeschlossen, sofern seitens des Autors kein nachweislich vorsätzliches oder grob fahrlässiges Verschulden vorliegt. Alle Angebote sind freibleibend und unverbindlich. Der Autor behält es sich ausdrücklich vor, Teile der Seiten oder das gesamte Angebot ohne gesonderte Ankündigung zu verändern, zu ergänzen, zu löschen oder die Veröffentlichung zeitweise oder endgültig einzustellen.
</p>
<br>
<h3>
  2. Verweise und Links
</h3>
<p>
  Bei direkten oder indirekten Verweisen auf fremde Internetseiten („Links“), die außerhalb des Verantwortungsbereiches des jeweiligen Autors liegen, würde eine Haftungsverpflichtung ausschließlich in dem Fall in Kraft treten, in dem der Autor von den Inhalten Kenntnis hat und es ihm technisch möglich und zumutbar wäre, die Nutzung im Falle rechtswidriger Inhalte zu verhindern.
  Der Autor erklärt hiermit ausdrücklich, dass zum Zeitpunkt der Linksetzung keine illegalen Inhalte auf den zu verlinkenden Seiten erkennbar waren. Auf die aktuelle und zukünftige Gestaltung, die Inhalte oder die Urheberschaft der gelinkten/verknüpften Seiten hat der Autor keinerlei Einfluss. Deshalb distanziert er sich hiermit ausdrücklich von allen Inhalten aller gelinkten /verknüpften Seiten, die nach der Linksetzung verändert wurden. Diese Feststellung gilt für alle innerhalb des eigenen Internetangebotes gesetzten Links und Verweise sowie für Fremdeinträge in vom Autor eingerichteten Gästebüchern, Diskussionsforen und Mailinglisten. Für illegale, fehlerhafte oder unvollständige Inhalte und insbesondere für Schäden, die aus der Nutzung oder Nichtnutzung solcherart dargebotener Informationen entstehen, haftet allein der Anbieter der Seite, auf welche verwiesen wurde, nicht derjenige, der über Links auf die jeweilige Veröffentlichung lediglich verweist.
</p>
<br>
<h3>
  3. Urheber- und Kennzeichenrecht
</h3>
<p>
  Der jeweilige Autor ist bestrebt, in allen Publikationen die Urheberrechte der verwendeten Grafiken, Tondokumente, Videosequenzen und Texte zu beachten, von ihm selbst erstellte Grafiken, Tondokumente, Videosequenzen und Texte zu nutzen oder auf lizenzfreie Grafiken, Tondokumente, Videosequenzen und Texte zurückzugreifen.
  Alle innerhalb des Internetangebotes genannten und ggf. durch Dritte geschätzten Marken- und Warenzeichen unterliegen uneingeschränkt den Bestimmungen des jeweils gültigen Kennzeichenrechts und den Besitzrechten der jeweiligen eingetragenen Eigentümer. Allein aufgrund der bloßen Nennung ist nicht der Schluss zu ziehen, dass Markenzeichen nicht durch Rechte Dritter geschützt sind!
  Das Copyright für veröffentlichte, vom Autor selbst erstellte Objekte bleibt allein beim Autor der Seiten. Eine Vervielfältigung oder Verwendung solcher Grafiken, Tondokumente, Videosequenzen und Texte in anderen elektronischen oder gedruckten Publikationen ist ohne ausdrückliche Zustimmung des Autors nicht gestattet.. Datenschutz

  Sofern innerhalb des Internetangebotes die Möglichkeit zur Eingabe persönlicher oder geschäftlicher Daten (Emailadressen, Namen, Anschriften) besteht, so erfolgt die Preisgabe dieser Daten seitens des Nutzers auf ausdrücklich freiwilliger Basis. Die Inanspruchnahme und Bezahlung aller angebotenen Dienste ist – soweit technisch möglich und zumutbar – auch ohne Angabe solcher Daten bzw. unter Angabe anonymisierter Daten oder eines Pseudonyms gestattet.
<p>
<br>
<h3>
  5. Rechtswirksamkeit dieses Haftungsausschlusses
</h3>
<p>
  Dieser Haftungsausschluss ist als Teil des Internetangebotes zu betrachten, von dem aus auf diese Seite verwiesen wurde. Sofern Teile oder einzelne Formulierungen dieses Textes der geltenden Rechtslage nicht, nicht mehr oder nicht vollständig entsprechen sollten, bleiben die übrigen Teile des Dokumentes in ihrem Inhalt und ihrer Gültigkeit davon unberührt.
</p>
<br>
<h3>
  6. Kaufvertrag
</h3>
<p>
  Zwischen der FrachtenFuchs UG und dem Kunden kommt es beim Klick auf "Jetzt zahlungspflichtig bestellen" zu einem Kaufvertrag, der vor Lieferung der Ware zu bedienen ist.
</p>
<br>
<h3>
  7. Abwicklung
</h3>
<ol>
  <li>Produkte werden durch Kunden bestellt</li>
  <li>Bestellte Produkte werden vollständig durch Überweisung auf das genannte Konto der FrachtenFuchs  UG bezahlt</li>
  <li>Nach vollständigem Geldeingang wird die Ware gekauft und an den Kunden verschickt (Lieferzeit meist 1-2 Tage)</li>
  <li>Nach Lieferung der Ware wird diese an den Kunden gemäß der Adresse aus der Bestellung weitergeschickt</li>
</ol>
<br>
<h3>8. Stornierung</h3>
<p>
  Bis zum Zeitpunkt der Liferung Ware durch den Importeur kann die Bestellung kostenfrei zu Geschäftszeiten storniert werden.
</p>
<br>
<h3>9. Cookies</h3>
<p>
  Mit der Nutzung des Shops erklärt sich der Kunde mit der Nutzung eines Cookies zur Bestellabwicklung und mit der Weitergabe und der Nutzung von Google Analytics einverstanden.<br><br>
  "Tracking":<br> Es wird Google Analytics verwendet.
</p>
<h3>Datenschutz</h3>
<p>
  Daten des Kunden werden ausschließlich im Rahmen des Trackings (siehe 9.), der Durchführung der Bestellung und der Bestellabwicklung erfasst.
</p>

app/views/main/imprint.html.erb
<h1>Impressum</h1>
<p>
FrachtenFuchs UG (haftungsbeschränkt)<br>
Julian Hauck (Geschäftsführer)<br>
<br>
Adresse:<br>
Siegburger Straße 62<br>
53229 Bonn<br>
<br>
Telefon:<br>
+49 - (0)176 2004 33 77<br>
<br>
E-Mail:<br>
julian.chandrahauck@gmail.com<br>
<br>
Bank:<br>
BIC: HOLVDEB1<br>
IBAN: DE92100179972590672794
</p>

app/views/main/landing_page.html.erb
<p>.</p>
<style>
  body {
    background-image: url('logo-bs-transparent.png');
    background-repeat: no-repeat;
    background-size: 200px;
    display: block;
    margin-left: auto;
    margin-right: auto;
  }
</style>
<br><br><br><br><br><br>
<h1>Herzlich Willkommen in unserem Spirit-Shop!</h1>
<br>
<p>Wir verkaufen ausgewählte und qualitativ hochwertige Spirits zu einem sehr günstigen Preis</p>
<br><br>
<p>Hauptsächlich für:</p>
<ul>
  <li><%= link_to 'Scotch', scotch_path %></li>
  <li><%= link_to 'Whiskey', whiskey_path %></li>
  <li><%= link_to 'Rum', rum_path %></li>
  <li><%= link_to 'Gin', gin_path %></li>
  <li><%= link_to '...Andere', andere_path %></li>
</ul>

<p>...aber wir verkaufen auch so allerlei andere Alkoholika aus aller Welt! (<%= link_to 'Zur Auswahl', andere_path %>)</p>

<br>

<h3>
 "billiger-schnaps.de" deshalb, weil wir Einkaufsrabatte nahezu 1:1 an Sie durchreichen! Also immer schön viel bestellen :-)
</h3>

<br>
<p>Viel Spaß in unserem Web-Shop und bei Fragen können Sie jederzeit anrufen (<%= link_to "Nummer", imprint_path %>)!</p>
<h4>Julian Hauck & S[ecret] D[istributeur] :-)</h4>
<p>--------------------------------------------------------------------------------------------</p>
<h3>Produkte (Netto Preise)</h3>
<table>
<% Product.without_versand.sort_by(&:created_at).each do |p| %>
  <tr>
    <td><%= link_to p.title, p %> - <%= number_with_precision(p.net, precision: 2) %> €</td>
  </tr>
<% end %>
</table>