config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Area 1: Admin
  namespace :admin do
    root to: 'home#index'
    match 'sign_in', :ur => "authentication#sign_in", via: :get
    match 'login', :to => "authentication#login", via: :post
    resources :products
    resources :kirsch_products
    resources :users
    resources :orders, only: [ :index ]
    namespace :orders do
      get :mark_paid, as: :mark_paid
      get :mark_sent, as: :mark_sent
      get :mark_fake, as: :mark_fake
      get :ordered_at_kirsch, as: :ordered_at_kirsch
      get :fake
    end
    get 'empty', to: 'home#empty'
    get 'reporting', to: 'home#reporting'
  end

  # Area 2: customer
  root to: 'main#landing_page'
  resources :orders, only: [:new, :create, :show]
  post 'orders/entry', to: 'orders#entry', as: 'entry'
  resources :products, only: [:show]

  get 'scotch', to: 'main#scotch', as: :scotch
  get 'whiskey', to: 'main#whiskey', as: :whiskey
  get 'rum', to: 'main#rum', as: :rum
  get 'gin', to: 'main#gin', as: :gin
  get 'andere', to: 'main#andere', as: :andere

  # Area 3: static pages
  get 'imprint', to: 'main#imprint'
  get 'agb', to: 'main#agb'
  get 'therapien', to: 'main#therapien'
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items

  validates :address, presence: true
  validates :email, presence: true, format: Devise.email_regexp

  accepts_nested_attributes_for :order_items, :allow_destroy => true

  before_save :save_prices

  def gross
    read_attribute(:gross) || order_items.sum(&:gross)
  end

  def net
    read_attribute(:net) || order_items.sum(&:net)
  end

  def vat
    read_attribute(:vat) || order_items.sum(&:vat)
  end

  def sent?
    !!read_attribute(:sent)
  end

  def pay!
    write_attribute(:paid, true)
  end

  def sent!
    write_attribute(:sent, true)
  end

  private

  def save_prices
    write_attribute(:net, order_items.sum(&:net))
    write_attribute(:vat, order_items.sum(&:vat))
    write_attribute(:gross, order_items.sum(&:gross))
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminController
  def index
    true_orders
  end

  def mark_paid
    true_orders
    @order = Order.find(params[:order_id])
    @order.paid = true
    @order.save!
    redirect_to :admin_orders
  end

  def mark_sent
    true_orders
    @order = Order.find(params[:order_id])
    @order.sent = true
    @order.save!
    redirect_to :admin_orders
  end

  def mark_fake
    true_orders
    @order = Order.find(params[:order_id])
    @order.fake = true
    @order.save!
    redirect_to :admin_orders
  end

  def mark_ordered_at_kirsch
    true_orders
    @order = Order.find(params[:order_id])
    @order.orderd_at_kirsch = true
    @order.save!
    redirect_to :admin_orders
  end

  def fake
    @orders = Order.where(fake: true).all
  end

  private

  def true_orders
    @orders = Order.where(fake: false).all.sort_by(&:created_at).reverse
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # Step 1/3
  # prepare by selecting products
  def new
    @order = Order.new
    @order.order_items = OrderItem.with_versand
  end

  # Step 2/3
  # customer data entry
  def entry
    params.permit!
    @order = Order.new(params[:order])
    @order.order_items = @order.order_items.select  {|oi| oi.quantity == 1}
  end

  # Step 3/3
  # conduct order
  def create
    params.permit!
    @order = Order.new(params[:order])
    if @order.save
      OrderConfirmatorMailer.confirm(@order).deliver_now
      redirect_to @order
    else
      render html: "FEHLER! E-Mail richtig? Ansonsten anrufen #{TheCompany.phone}"
    end
  end

  def show # thank you page
    @order = Order.find(params[:id])
  end
end

app/views/admin/orders/fake.html.erb
<%= render 'admin/nav' %>

<h1>Fake Orders</h1>

<table border="1">
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Address</th>
    <th>E-Mail</th>
    <th>Ordered At</th>
  </tr>

  <% @orders.each do |o| %>
    <tr>
      <td><%= o.id %></td>
      <td><%= o.name %></td>
      <td><%= o.address  %></td>
      <td><%= o.email %></td>
      <td align='right'>
        <%= o.created_at.strftime('%F') %><br>
        <%= o.created_at.strftime('%H:%M') %> GMT
      </td>
    </tr>
  <% end %>
</table>

app/views/admin/orders/index.html.erb
<%= render 'admin/nav' %>

<h1>Orders (Chronologically Reverse)</h1>

<table border="1">
  <tr>
    <th>ID</th>
    <th>Fake</th>
    <th>Name</th>
    <th>Address</th>
    <th>E-Mail</th>
    <th>Net Price</th>
    <th>VAT</th>
    <th>Gross Price</th>
    <th>Paid?</th>
    <th>Ordered At</th>
    <th>Ordered Items</th>
    <th>Paid?</th>
    <th>Ordered at Kirsch?</th>
    <th>Sent?</th>
    <th>Actions</th>
  </tr>

  <% @orders.each do |o| %>
    <tr>
      <td><%= o.id %></td>
      <td><%= "X" unless !!o.fake %></td>
      <td><%= o.name %></td>
      <td><%= o.address  %></td>
      <td><%= o.email %></td>
      <td align='right'><%= number_with_precision(o.net, precision: 2) %> €</td>
      <td align='right'><%= number_with_precision(o.vat, precision: 2) %> €</td>
      <td align='right'><%= number_with_precision(o.gross, precision: 2) %> €</td>
      <td>
        <%=  o.paid?%>
      </td>
      <td align='right'>
        <%= o.created_at.strftime('%F') %><br>
        <%= o.created_at.strftime('%H:%M') %> GMT
      </td>
      <td align='right'>
        <table border="1">
          <tr>
            <th>Title</th>
            <th>Quantity</th>
            <th>Net Price</th>
            <th>VAT</th>
            <th>Gross Price</th>
          </tr>
          <% o.order_items.each do |oi| %>
            <tr>
              <td align='left'><%= oi.title %></td>
              <td align='left'><%= oi.quantity %></td>
              <td align='left'><%= number_with_precision(oi.net, precision: 2) %> €</td>
              <td align='left'><%= number_with_precision(oi.vat, precision: 2) %> €</td>
              <td align='left'><%= number_with_precision(oi.gross, precision: 2) %> €</td>
            </tr>
          <% end %>
        </table>
      </td>
      <td><%= o.paid? %></td>
      <td><%= o.ordered_at_kirsch? %></td>
      <td><%= o.sent? %></td>
      <td><%= o.fake? %></td>
      <td>
        <%= link_to('Mark Paid', admin_orders_mark_paid_path(order_id: o.id)) unless o.paid? %><br><br>
        <%= link_to('Mark Ordered at Kirsch', admin_orders_mark_sent_path(order_id: o.id)) unless o.ordered_at_kirsch? %><br><br>
        <%= link_to('Mark Sent', admin_orders_mark_sent_path(order_id: o.id)) unless o.sent? %><br><br>
        <%= link_to('Mark Fake', admin_orders_mark_fake_path(order_id: o.id))  unless o.fake? %>
      </td>
    </tr>
  <% end %>
</table>